export const COUNTRIES = [
  { code: "ES", name: "Espana", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "US", name: "Estados Unidos", flag: "\u{1F1FA}\u{1F1F8}" },
  { code: "DE", name: "Alemania", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "FR", name: "Francia", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "GB", name: "Reino Unido", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "AE", name: "Emiratos Arabes", flag: "\u{1F1E6}\u{1F1EA}" },
  { code: "SA", name: "Arabia Saudita", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "CA", name: "Canada", flag: "\u{1F1E8}\u{1F1E6}" },
  { code: "AU", name: "Australia", flag: "\u{1F1E6}\u{1F1FA}" },
  { code: "PT", name: "Portugal", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "IT", name: "Italia", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "NL", name: "Paises Bajos", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "BE", name: "Belgica", flag: "\u{1F1E7}\u{1F1EA}" },
  { code: "CH", name: "Suiza", flag: "\u{1F1E8}\u{1F1ED}" },
  { code: "AT", name: "Austria", flag: "\u{1F1E6}\u{1F1F9}" },
  { code: "SE", name: "Suecia", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "NO", name: "Noruega", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "DK", name: "Dinamarca", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "MX", name: "Mexico", flag: "\u{1F1F2}\u{1F1FD}" },
  { code: "CO", name: "Colombia", flag: "\u{1F1E8}\u{1F1F4}" },
  { code: "PE", name: "Peru", flag: "\u{1F1F5}\u{1F1EA}" },
  { code: "AR", name: "Argentina", flag: "\u{1F1E6}\u{1F1F7}" },
  { code: "CL", name: "Chile", flag: "\u{1F1E8}\u{1F1F1}" },
  { code: "BR", name: "Brasil", flag: "\u{1F1E7}\u{1F1F7}" },
  { code: "EC", name: "Ecuador", flag: "\u{1F1EA}\u{1F1E8}" },
  { code: "VE", name: "Venezuela", flag: "\u{1F1FB}\u{1F1EA}" },
  { code: "CZ", name: "República Checa", flag: "🇨🇿" },
  { code: "DO", name: "Republica Dominicana", flag: "\u{1F1E9}\u{1F1F4}" },
  { code: "GT", name: "Guatemala", flag: "\u{1F1EC}\u{1F1F9}" },
  { code: "HN", name: "Honduras", flag: "\u{1F1ED}\u{1F1F3}" },
  { code: "SV", name: "El Salvador", flag: "\u{1F1F8}\u{1F1FB}" },
  { code: "NI", name: "Nicaragua", flag: "\u{1F1F3}\u{1F1EE}" },
  { code: "CR", name: "Costa Rica", flag: "\u{1F1E8}\u{1F1F7}" },
  { code: "PA", name: "Panama", flag: "\u{1F1F5}\u{1F1E6}" },
  { code: "PH", name: "Filipinas", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "IN", name: "India", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "PK", name: "Pakistan", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "BD", name: "Bangladesh", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "MA", name: "Marruecos", flag: "\u{1F1F2}\u{1F1E6}" },
  { code: "EG", name: "Egipto", flag: "\u{1F1EA}\u{1F1EC}" },
  { code: "NG", name: "Nigeria", flag: "\u{1F1F3}\u{1F1EC}" },
  { code: "KE", name: "Kenia", flag: "\u{1F1F0}\u{1F1EA}" },
] as const;

export const SECTORS = [
  { value: "construction", label: "construction" },
  { value: "hotel_tourism", label: "hotelAndTourism" },
  { value: "agriculture", label: "agriculture" },
  { value: "manufacturing", label: "manufacturing" },
  { value: "technology", label: "technology" },
  { value: "health", label: "health" },
  { value: "transport_logistics", label: "transportAndLogistics" },
  { value: "energy", label: "energy" },
  { value: "commerce", label: "commerce" },
  { value: "domestic_services", label: "domesticServices" },
] as const;

export const JOB_TYPES = [
  { value: "full_time", label: "fullTime" },
  { value: "part_time", label: "partTime" },
  { value: "contract", label: "contract" },
  { value: "seasonal", label: "seasonal" },
] as const;
